#   _           _                             _                 _
#  | |  _ __   | |_   ___   __   ___   _ _   | |_   _ _   ___  | |
#  | | | '  \  |  _| |___| / _| / _ \ | ' \  |  _| | '_| / _ \ | |
#  |_| |_|_|_|  \__|       \__| \___/ |_||_|  \__| |_|   \___/ |_|
#
tasks:
   - name: cloggy
     before:  clogrc/gitpod-tasks.sh before
     init:    clogrc/gitpod-tasks.sh init
     command: clogrc/gitpod-tasks.sh command

# port for preview server
ports:
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - dbaeumer.vscode-eslint            # lint javascript code
    - piersdeseilligny.betterfountain   # screen writer plugin
    - stkb.rewrap                       # wrap markdown at column boundaries
    - ms-toolsai.jupyter                # jupyter notebook support
    - ms-toolsai.jupyter-keymap         # jupyter notebook support
    - ms-toolsai.jupyter-renderers      # jupyter notebook support
    - mads-hartmann.bash-ide-vscode     # bash scripting helper
